[package]
name = "busy_beaver_reduction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4" 
itertools = "0.10.0"
env_logger = "0.11"
threadpool = "1.8.1"